// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
//import 'package:flutter/foundation.dart'
    //show defaultTargetPlatform, kIsWeb, TargetPlatform;
FirebaseOptions  firebaseOptions = const FirebaseOptions(
  apiKey: 'AIzaSyBZasXCeOr1T-J2RbqLO3bM7XHyLazWzZY',
  appId: '1:921724158167:android:ed919833c4f329b80f3092',
  messagingSenderId: '921724158167',
  projectId: 'soricc-1e85a',
  storageBucket: 'soricc-1e85a.appspot.com',
);

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/*
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYTrpVITkUKgbfp4sAcPDxMluOSN15h8I',
    appId: '1:921724158167:web:40200664477c40c40f3092',
    messagingSenderId: '921724158167',
    projectId: 'soricc-1e85a',
    authDomain: 'soricc-1e85a.firebaseapp.com',
    storageBucket: 'soricc-1e85a.appspot.com',
  );



  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_UU7i_XHY2_Sd4Hna9YZqwAVmJDOs_KE',
    appId: '1:921724158167:ios:bbea90cd17cbf6770f3092',
    messagingSenderId: '921724158167',
    projectId: 'soricc-1e85a',
    storageBucket: 'soricc-1e85a.appspot.com',
    iosBundleId: 'com.example.soricc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_UU7i_XHY2_Sd4Hna9YZqwAVmJDOs_KE',
    appId: '1:921724158167:ios:bbea90cd17cbf6770f3092',
    messagingSenderId: '921724158167',
    projectId: 'soricc-1e85a',
    storageBucket: 'soricc-1e85a.appspot.com',
    iosBundleId: 'com.example.soricc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYTrpVITkUKgbfp4sAcPDxMluOSN15h8I',
    appId: '1:921724158167:web:0dcbf3d23016ffee0f3092',
    messagingSenderId: '921724158167',
    projectId: 'soricc-1e85a',
    authDomain: 'soricc-1e85a.firebaseapp.com',
    storageBucket: 'soricc-1e85a.appspot.com',
  );
}
*/